### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by ASingh1976** [freedev/adobe-omniture-api-rest-java#1]
Hi,

I used your code, but I am getting below error

18:37:01.989 [main] DEBUG o.a.h.i.c.DefaultClientConnectionOperator - Connecting to api.omniture.com:443
javax.ws.rs.ProcessingException: Unable to invoke request
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to https://api.omniture.com refused

-Regards
  Anurag

**Comment by freedev** [comment]
## This project is deprecated and has no maintenance.
